apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "7dtd.fullname" . }}-config
  labels:
    {{- include "7dtd.labels" . | nindent 4 }}
data:
  mkserveradmin.sh: |
    #!/bin/bash
    #
    # Generate the serveradmin.xml file.
    #
    set -e

    CFG_FILE="/app/world/Saves/serveradmin.xml"
    CFG_DIR="$(dirname "$CFG_FILE")"
    mkdir -p "$CFG_DIR"

    cat<<EOF >"$CFG_FILE"
    <?xml version="1.0" encoding="UTF-8"?>
    <!--
            This file holds the settings for who is banned, whitelisted,
            admins and server command permissions. The admin and whitelist sections can contain
            both individual Steam users as well as Steam groups.

            STEAM ID INSTRUCTIONS:
            ===============================================================
            You can find the SteamID64 of any user with one of the following pages:
            https://steamdb.info/calculator/, https://steamid.io/lookup, http://steamid.co/
            http://steamid.co/ instructions:
            Input the player's name in the search field. example: Kinyajuu
            If the name doesn't work, you can also use the url of their steam page.
            Also you may add/remove admins, mods, whitelist, blacklist using in game commands.
            You will want the STEAM64ID. example: 76561198021925107

            STEAM GROUP ID INSTRUCTIONS:
            ===============================================================
            You can find the SteamID64 of any group by taking its address and adding
              /memberslistxml/?xml=1
            to the end. You will get the XML information of the group which should have an entry
            memberList->groupID64.
            Example: The 'Steam Universe' group has the address
              https://steamcommunity.com/groups/steamuniverse
            So you point your browser to
              https://steamcommunity.com/groups/steamuniverse/memberslistxml/?xml=1
            And see that the groupID64 is 103582791434672565.

            XBOX LIVE ID INSTRUCTIONS:
            ===============================================================
            Check the client or server log for the PXUID of a player or use the console commands to add players
            to the list.

            PERMISSION LEVEL INSTRUCTIONS:
            ===============================================================
            permission level : 0-1000, a user may run any command equal to or above their permission level.
            Users not given a permission level in this file will have a default permission level of 1000!

            COMMAND PERMISSIONS INSTRUCTIONS:
            ===============================================================
            cmd : This is the command name, any command not in this list will not be usable by anyone but the server.
            permission level : 0-1000, a user may run any command equal to or above their permission level.
            Commands not specified in this file will have a default permission level of 0!

            EVERYTHING BETWEEN <!- - and - -> IS COMMENTED OUT! THE ENTRIES BELOW ARE EXAMPLES THAT ARE NOT ACTIVE!!!
    -->
    {{- with .Values.userConfig }}
    <adminTools>
      <!-- Name in any entries is optional for display purposes only -->
      <users>
        {{- range .users }}
        <user platform="Steam" userid="{{ .steamID }}" name="{{ .name }}" permission_level="{{ .permissionLevel }}" />
        {{- end }}
        {{- range .groups }}
        <group steamID="{{ .steamID }}" name="{{ .name }}" permission_level_default="{{ .permissionLevelDefault }}" permission_level_mod="{{ .permissionLevelMod }}" />
        {{- end }}
      </users>
      <whitelist>
        {{- range .whitelistUsers }}
        <user platform="Steam" userid="{{ .steamID }}" name="{{ .name }}" />
        {{- end }}
        {{- range .whitelistGroups }}
        <group steamID="{{ .steamID }}" name="{{ .name }}" />
        {{- end }}
      </whitelist>
      <blacklist>
        {{- range .blacklist }}
        <blacklisted platform="Steam" userid="{{ .steamID }}" name="{{ .name }}" unbandate="{{ .unbanDate }}" reason="{{ .reason }}" />
        {{- end }}
      </blacklist>
      <commands>
        <!-- <permission cmd="dm" permission_level="0" /> -->
        <!-- <permission cmd="kick" permission_level="1" /> -->
        <!-- <permission cmd="say" permission_level="1000" /> -->
        <permission cmd="chunkcache" permission_level="1000" />
        <permission cmd="createwebuser" permission_level="1000" />
        <permission cmd="debugshot" permission_level="1000" />
        <permission cmd="debugweather" permission_level="1000" />
        <permission cmd="decomgr" permission_level="1000" />
        <permission cmd="getgamepref" permission_level="1000" />
        <permission cmd="getgamestat" permission_level="1000" />
        <permission cmd="getlogpath" permission_level="1000" />
        <permission cmd="getoptions" permission_level="1000" />
        <permission cmd="gettime" permission_level="1000" />
        <permission cmd="gfx" permission_level="1000" />
        <permission cmd="graph" permission_level="1000" />
        <permission cmd="help" permission_level="1000" />
        <permission cmd="listplayerids" permission_level="1000" />
        <permission cmd="listthreads" permission_level="1000" />
        <permission cmd="loot" permission_level="1000" />
        <permission cmd="memcl" permission_level="1000" />
        <permission cmd="settempunit" permission_level="1000" />
        <permission cmd="uioptions" permission_level="1000" />
      </commands>
      <apitokens>
        <!-- <token name="adminuser1" secret="supersecrettoken" permission_level="0" /> -->
      </apitokens>
      <webmodules />
      <webusers />
    </adminTools>
    {{- end }}
    EOF

    echo "Wrote $CFG_FILE"
    chown -R 7days:7days "$CFG_DIR"

  mkservercfg.sh: |
    #!/bin/bash
    #
    # Generate the serverconfig.xml file.
    #
    set -e

    CFG_FILE="/app/7-days-to-die/serverconfig.xml"
    SERVER_PASSWORD=""
    TELNET_PASSWORD=""

    SERVER_PASSWORD_SECRET="{{ .Values.serverConfig.server.serverPasswordSecret }}"
    if [[ -n "$SERVER_PASSWORD_SECRET" ]]; then
      SERVER_PASSWORD="$(cat /secrets/server/password)"
    fi

    TELNET_PASSWORD_SECRET="{{ .Values.serverConfig.admin.telnetPasswordSecret }}"
    if [[ -n "$TELNET_PASSWORD_SECRET" ]]; then
      TELNET_PASSWORD="$(cat /secrets/telnet/password)"
    fi

    cat<<EOF >"$CFG_FILE"
    <?xml version="1.0"?>
    {{- with .Values.serverConfig }}
    <ServerSettings>
      <!-- GENERAL SERVER SETTINGS -->

      <!-- Server representation -->
      {{- with .server }}
      <property name="ServerName" value="{{ .serverName }}"/>
      <property name="ServerDescription" value="{{ .serverDescription }}"/>
      <property name="ServerWebsiteURL" value="{{ .serverWebsiteUrl }}"/>
      <property name="ServerPassword" value="$SERVER_PASSWORD" />
      <property name="ServerLoginConfirmationText" value="{{ .serverLoginConfirmationText }}" />
      <property name="Region" value="{{ .region }}" />
      <property name="Language" value="{{ .language }}" />
      {{- end }}

      <!-- Networking -->
      {{- with .networking }}
      <property name="ServerPort" value="{{ .serverPort }}"/>
      <property name="ServerVisibility" value="{{ .serverVisibility }}"/>
      <property name="ServerDisabledNetworkProtocols"	value="{{ .serverDisabledNetworkProtocols }}"/>
      <property name="ServerMaxWorldTransferSpeedKiBs" value="{{ .serverMaxWorldTransferSpeedKiBs }}"/>
      {{- end }}

      <!-- Slots -->
      {{- with .slots }}
      <property name="ServerMaxPlayerCount" value="{{ .serverMaxPlayerCount }}" />
      <property name="ServerReservedSlots" value="{{ .serverReservedSlots }}"/>
      <property name="ServerReservedSlotsPermission" value="{{ .serverReservedSlotsPermission }}"/>
      <property name="ServerAdminSlots" value="{{ .serverAdminSlots }}"/>
      <property name="ServerAdminSlotsPermission" value="{{ .serverAdminSlotsPermission }}"/>
      {{- end }}

      <!-- Admin interfaces -->
      {{- with .admin }}
      <property name="WebDashboardEnabled" value="{{ .webDashboardEnabled }}"/>
      <property name="WebDashboardPort" value="{{ .webDashboardPort }}"/>
      <property name="WebDashboardUrl" value="{{ .webDashboardUrl }}"/>
      <property name="EnableMapRendering" value="{{ .enableMapRendering }}"/>

      <property name="TelnetEnabled" value="{{ .telnetEnabled }}"/>
      <property name="TelnetPort" value="{{ .telnetPort }}"/>
      <property name="TelnetPassword" value="$TELNET_PASSWORD"/>
      <property name="TelnetFailedLoginLimit" value="{{ .telnetFailedLoginLimit }}"/>
      <property name="TelnetFailedLoginsBlocktime" value="{{ .telnetFailedLoginsBlocktime }}"/>

      <property name="TerminalWindowEnabled" value="false"/>
      {{- end }}

      <!-- Folder and file locations -->
      <property name="AdminFileName" value="serveradmin.xml"/>
      <property name="UserDataFolder" value="/app/world" />

      <!-- Other technical settings -->
      {{- with .other }}
      <property name="EACEnabled" value="{{ .eacEnabled }}"/>
      <property name="IgnoreEOSSanctions" value="{{ .ignoreEOSSanctions }}"/>
      <property name="HideCommandExecutionLog" value="{{ .hideCommandExecutionLog }}"/>
      <property name="MaxUncoveredMapChunksPerPlayer" value="{{ .maxUncoveredMapChunksPerPlayer }}"/>
      <property name="PersistentPlayerProfiles" value="{{ .persistentPlayerProfiles }}" />
      <property name="MaxChunkAge" value="{{ .maxChunkAge }}"/>
      <property name="SaveDataLimit" value="{{ .saveDataLimit }}"/>
      {{- end }}

      <!-- GAMEPLAY -->
      {{- with .gameplay }}

      <!-- World -->
      {{- with .world }}
      <property name="GameWorld" value="{{ .gameWorld }}"/>
      <property name="WorldGenSeed" value="{{ .worldGenSeed }}"/>
      <property name="WorldGenSize" value="{[ .worldGenSize ]}"/>
      <property name="GameName" value="{{ .gameName }}"/>
      <property name="GameMode" value="{{ .gameMode }}"/>
      {{- end }}

      <!-- Difficulty -->
      {{- with .difficulty }}
      <property name="GameDifficulty" value="{{ .gameDifficulty }}"/>
      <property name="BlockDamagePlayer" value="{{ .blockDamagePlayer }}" />
      <property name="BlockDamageAI" value="{{ .blockDamageAI }}" />
      <property name="BlockDamageAIBM" value="{{ .blockDamageAIBM }}" />
      <property name="XPMultiplier" value="{{ .xpMultiplier }}" />
      <property name="PlayerSafeZoneLevel" value="{{ .playerSafeZoneLevel }}" />
      <property name="PlayerSafeZoneHours" value="{{ .playerSafeZoneHours }}" />
      {{- end }}

      <!-- Misc. -->
      {{- with .misc }}
      <property name="BuildCreate" value="{{ .buildCreate }}" />
      <property name="DayNightLength" value="{{ .dayNightLength }}" />
      <property name="DayLightLength" value="{{ .dayLightLength }}" />
      <property name="DeathPenalty" value="{{ .deathPenalty }}" />
      <property name="DropOnDeath" value="{{ .dropOnDeath }}" />
      <property name="DropOnQuit" value="{{ .dropOnQuit }}" />
      <property name="BedrollDeadZoneSize" value="{{ .bedrollDeadZoneSize }}" />
      <property name="BedrollExpiryTime" value="{{ .bedrollExpiryTime }}" />

      <property name="DynamicMeshEnabled" value="{{ .dynamicMeshEnabled }}"/>
      <property name="DynamicMeshLandClaimOnly" value="{{ .dynamicMeshLandClaimOnly }}"/>
      <property name="DynamicMeshLandClaimBuffer" value="{{ .dynamicMeshLandClaimBuffer }}"/>
      <property name="DynamicMeshMaxItemCache" value="{{ .dynamicMeshMaxItemCache }}"/>

      <property name="TwitchServerPermission" value="{{ .twitchServerPermission }}"/>
      <property name="TwitchBloodMoonAllowed" value="{{ .twitchBloodMoonAllowed }}"/>

      <property name="QuestProgressionDailyLimit" value="{{ .questProgressionDailyLimit }}"/>
      {{- end }}

      <!-- Performance related -->
      {{- with .performance }}
      <property name="MaxSpawnedZombies" value="{{ .maxSpawnedZombies }}" />
      <property name="MaxSpawnedAnimals" value="{{ .maxSpawnedAnimals }}" />
      <property name="ServerMaxAllowedViewDistance" value="{{ .serverMaxAllowedViewDistance }}" />
      <property name="MaxQueuedMeshLayers" value="{{ .maxQueuedMeshLayers }}" />
      {{- end }}

      <!-- Zombie settings -->
      {{- with .zombie }}
      <property name="EnemySpawnMode" value="{{ .enemySpawnMode }}" />
      <property name="EnemyDifficulty" value="{{ .enemyDifficulty }}" />
      <property name="ZombieFeralSense" value="{{ .zombieFeralSense }}" />
      <property name="ZombieMove" value="{{ .zombieMove }}" />
      <property name="ZombieMoveNight" value="{{ .zombieMoveNight }}" />
      <property name="ZombieFeralMove" value="{{ .zombieFeralMove }}" />
      <property name="ZombieBMMove" value="{{ .zombieBMMove }}" />
      <property name="BloodMoonFrequency" value="{{ .bloodMoonFrequency }}" />
      <property name="BloodMoonRange" value="{{ .bloodMoonRange }}" />
      <property name="BloodMoonWarning" value="{{ .bloodMoonWarning }}" />
      <property name="BloodMoonEnemyCount" value="{{ .bloodMoonEnemyCount }}" />
      {{- end }}

      <!-- Loot -->
      {{- with .loot }}
      <property name="LootAbundance" value="{{ .lootAbundance }}" />
      <property name="LootRespawnDays" value="{{ .lootRespawnDays }}" />
      <property name="AirDropFrequency" value="{{ .airDropFrequency }}"/>
      <property name="AirDropMarker" value="{{ .airDropMarker }}"/>
      {{- end }}

      <!-- Multiplayer -->
      {{- with .multiplayer }}
      <property name="PartySharedKillRange" value="{{ .partySharedKillRange }}"/>
      <property name="PlayerKillingMode" value="{{ .playerKillingMode }}" />
      {{- end }}

      <!-- Land claim options -->
      {{- with .landClaim }}
      <property name="LandClaimCount" value="{{ .landClaimCount }}"/>
      <property name="LandClaimSize" value="{{ .landClaimSize }}"/>
      <property name="LandClaimDeadZone" value="{{ .landClaimDeadZone }}"/>
      <property name="LandClaimExpiryTime" value="{{ .landClaimExpiryTime }}"/>
      <property name="LandClaimDecayMode" value="{{ .landClaimDecayMode }}"/>
      <property name="LandClaimOnlineDurabilityModifier" value="{{ .landClaimOnlineDurabilityModifier }}"/>
      <property name="LandClaimOfflineDurabilityModifier" value="{{ .landClaimOfflineDurabilityModifier }}"/>
      <property name="LandClaimOfflineDelay" value="{{ .landClaimOfflineDelay }}"/>
      {{- end }}
      {{- end }}{{/* with .gameplay */}}
    </ServerSettings>
    {{- end }}{{/* with .Values.serverConfig */}}
    EOF

    echo "Wrote $CFG_FILE"

    /config/mkserveradmin.sh
    exit 0
