{{- $haveSecrets := or .Values.serverConfig.server.serverPasswordSecret .Values.serverConfig.admin.telnetPasswordSecret }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "7dtd.fullname" . }}
  labels:
    {{- include "7dtd.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "7dtd.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "7dtd.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "7dtd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-config
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/config/mkservercfg.sh"]
          volumeMounts:
            - name: config
              mountPath: /config
            {{- if $haveSecrets }}
            - name: secrets
              mountPath: /secrets
            {{- end }}
            - name: game-files
              mountPath: /app/7-days-to-die
            - name: world
              mountPath: /app/world
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: game
              containerPort: {{ .Values.gameService.port }}
              protocol: TCP
            - name: dashboard
              containerPort: {{ .Values.webDashboardService.port }}
              protocol: TCP
            - name: telnet
              containerPort: {{ .Values.telnetService.port }}
              protocol: TCP
            {{- range untilStep 26900 26904 1 }}
            - name: game-udp-{{ . }}
              containerPort: {{ . }}
              protocol: UDP
            {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          startupProbe:
            tcpSocket:
              port: {{ .Values.gameService.port }}
            failureThreshold: {{ div .Values.startupDelaySeconds 10 }}
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: game-files
              mountPath: /app/7-days-to-die
            - name: world
              mountPath: /app/world
            - name: steam
              mountPath: /home/7days/.local/share/Steam
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "7dtd.fullname" . }}-config
            defaultMode: 0550
        - name: game-files
          persistentVolumeClaim:
            claimName: {{ include "7dtd.fullname" . }}-gamefiles
        - name: world
          persistentVolumeClaim:
            claimName: {{ include "7dtd.fullname" . }}-world
        - name: steam
          persistentVolumeClaim:
            claimName: {{ include "7dtd.fullname" . }}-steam
        {{- if $haveSecrets }}
        - name: secrets
          projected:
            sources:
              {{- if .Values.serverConfig.server.serverPasswordSecret }}
              - secret:
                  name: {{ .Values.serverConfig.server.serverPasswordSecret | quote }}
                  items:
                    - key: password
                      path: server/password
              {{- end }}
              {{- if .Values.serverConfig.admin.telnetPasswordSecret }}
              - secret:
                  name: {{ .Values.serverConfig.admin.telnetPasswordSecret | quote }}
                  items:
                    - key: password
                      path: telnet/password
              {{- end }}
        {{- end }}{{/* if $haveSecrets */}}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
