{{- if .Values.persistentStorage.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "7dtd.fullname" . }}-gamefiles
  labels:
    {{- include "7dtd.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.persistentStorage.gameFiles.className }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistentStorage.gameFiles.capacity | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "7dtd.fullname" . }}-steam
  labels:
    {{- include "7dtd.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.persistentStorage.steam.className }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistentStorage.steam.capacity | quote }}
{{- if .Values.backups.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "7dtd.fullname" . }}-backups
  labels:
    {{- include "7dtd.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.persistentStorage.backups.className }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistentStorage.backups.capacity | quote }}
{{- end }}{{/* if .Values.backups.enabled */}}
{{- end }}{{/* if .Values.persistentStorage.enabled */}}
