---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "7dtd.fullname" . }}-game
  labels:
    {{- include "7dtd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gameService.type }}
  ports:
    - port: {{ .Values.gameService.port }}
      targetPort: game
      protocol: TCP
      name: game
    {{- range untilStep 26900 26904 1 }}
    - port: {{ . }}
      targetPort: {{ . }}
      protocol: UDP
      name: game-udp-{{ . }}
    {{- end }}
  selector:
    {{- include "7dtd.selectorLabels" . | nindent 4 }}
{{- if .Values.serverConfig.admin.webDashboardEnabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "7dtd.fullname" . }}-dashboard
  labels:
    {{- include "7dtd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webDashboardService.type }}
  ports:
    - port: {{ .Values.webDashboardService.port }}
      targetPort: dashboard
      protocol: TCP
      name: dashboard
  selector:
    {{- include "7dtd.selectorLabels" . | nindent 4 }}
{{- end }}
{{- if .Values.serverConfig.admin.telnetEnabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "7dtd.fullname" . }}-telnet
  labels:
    {{- include "7dtd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.telnetService.type }}
  ports:
    - port: {{ .Values.telnetService.port }}
      targetPort: telnet
      protocol: TCP
      name: telnet
  selector:
    {{- include "7dtd.selectorLabels" . | nindent 4 }}
{{- end }}
